package org.example.model;

import org.example.util.Validate;
import java.util.Collections;
import java.util.List;

/** A survey with 1..3 multiple-choice questions. */
public final class Survey {
    private final long id;                 // generated by UI
    private final String title;
    private final List<Question> questions;

    public Survey(long id, String title, List<Question> questions) {
        this.id = id;
        this.title = Validate.requireText(title, "Survey title");
        Validate.requireSizeBetween(questions, 1, 3, "Questions");
        this.questions = Collections.unmodifiableList(questions);
    }

    public long getId() { return id; }
    public String getTitle() { return title; }
    public List<Question> getQuestions() { return questions; }

    @Override public String toString() { return "Survey{" + id + ", '" + title + "', q=" + questions.size() + "}"; }
}
